# Generated by Django 2.2.1 on 2019-07-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
        ),
    ]
